### ISSUE TITLE
Currency Conversion Error

### ISSUE THREAD

**Issue by melonaster3** [RSC-Labs/medusa-store-analytics#10]
For currencies, the amounts are calculated to dollars amount for all currencies.

![image](https://github.com/RSC-Labs/medusa-store-analytics/assets/101602590/e824bd3e-1c10-40d8-bff8-368087665db3)

The Korean currency, "won", was used to create the orders, and the total was about ₩47,040, but the analytics calculated the price system the same as dollars and it shows up as 470.40 KRW. 

![image](https://github.com/RSC-Labs/medusa-store-analytics/assets/101602590/5f7a0048-2968-4bd4-bf90-dfe4ef00c89d)

Same issue applies to the discount tab as well

**Comment by jamescjensen** [comment]
This should be solvable by obeying Medusa's currency model's decimal_digits field - when formatting prices, divide by `Math.pow(10, decimal_digits)` instead of a static 100, and for decimal places, use `.toFixed(decimal_digits)` instead of `.toFixed(2)`

**Comment by radoslaw-sz** [comment]
thanks @melonaster3 and @jamescjensen for your comments and tips. I will take a look and fix in the next days.

**Comment by radoslaw-sz** [comment]
hi @melonaster3  and @jamescjensen  - I hope I fixed it - possible fix is available in 0.11.0 version. Please check and let me know :)

**Comment by melonaster3** [comment]
Hey @radoslaw-sz , thanks for the fix! It looks good now. I'm going to close the issue but just a heads up for the formatting of all currencies, it would be nice if they can be formatted and  separated by commas like how medusa does it (Example 10000 -> 10,000).  Thanks regardless though appreciate the quick fix!

**Comment by radoslaw-sz** [comment]
@melonaster3  thanks, I will note it!
