### ISSUE TITLE
npm ERR! while trying to install plugin

### ISSUE THREAD

**Issue by SubhrajitDG** [RSC-Labs/medusa-store-analytics#14]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: medusa-starter-default@0.0.1
npm ERR! Found: @medusajs/medusa@1.20.7
npm ERR! node_modules/@medusajs/medusa
npm ERR!   @medusajs/medusa@"^1.20.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @medusajs/medusa@"1.20.1" from @rsc-labs/medusa-store-analytics@0.13.1
npm ERR! node_modules/@rsc-labs/medusa-store-analytics
npm ERR!   @rsc-labs/medusa-store-analytics@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.  

my Node version is - v21.5.0.
"@medusajs/medusa": "^1.20.6",

**Comment by radoslaw-sz** [comment]
hi @SubhrajitDG  - thank you for raising an issue. Indeed, probably I need to bump the version of medusajs which is used by the plugin (or adjust package.json to use more versions). 
I will fix it in the next days.

**Comment by radoslaw-sz** [comment]
hi @SubhrajitDG  - this was quite small fix, so you can try with the newest version - 0.13.2. I hope it will work now :)

**Comment by SubhrajitDG** [comment]
hi @radoslaw-sz , thanks for the quick fix. It installed perfectly
