### ISSUE TITLE
Any plans to update to Medusa v2

### ISSUE THREAD

**Issue by rozmyty** [RSC-Labs/medusa-store-analytics#35]
Great plugin! But.. any plans to update to Medusa v2?

**Comment by radoslaw-sz** [comment]
hi @rozmyty  - thank you for nice words!
Yes, the plan is to start migration to v2, but we are still waiting for the documentation how to build and publish to NPM...

**Comment by radoslaw-sz** [comment]
hi @rozmyty  - the migration to v2 has been started. If there won't be official documentation how to publish a plugin in v2, then the only option will be to copy everything from /src of plugin and paste into /src of Medusa project.

**Comment by radoslaw-sz** [comment]
hi @rozmyty  - plugin has been migrated - https://github.com/RSC-Labs/medusa-store-analytics/tree/main/v2. Enjoy!
